inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - ohdear_health_check.gemspec
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Lint/Debugger:
  Enabled: true
  Exclude: []
