name: Ruby

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
